blank_issues_enabled: false
contact_links:
  - name: Ask a general question
    url: https://github.com/ToolHive/toolhive/discussions
    about: For anything that doesn't fit into a feature request or bug report.
